# Welcome to numpy tutorial #

In [31]:
import numpy as np

In [2]:
x = np.array([[2,3,1,0]])

In [3]:
x

array([[2, 3, 1, 0]])

In [4]:
x[0][1]

3

In [5]:
x[0]

array([2, 3, 1, 0])

In [6]:
x[0][1]=23

In [7]:
x

array([[ 2, 23,  1,  0]])

In [8]:
x.dtype

dtype('int64')

In [9]:
x.shape

(1, 4)

# Array Creation #

In [32]:
x = np.array([[2,3,1,0],[4,5,6,7],[7,6,5,4]])

In [11]:
x

array([[2, 3, 1, 0],
       [4, 5, 6, 7],
       [7, 6, 5, 4]])

In [12]:
x.dtype

dtype('int64')

In [13]:
x.shape

(3, 4)

In [14]:
x.size

12

In [15]:
z = np.zeros((4, 5))

In [16]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lnspace = np.linspace(1,5,12)

In [19]:
lnspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
np = np.empty((4,6))

In [27]:
np

array([[1.79696023e-316, 0.00000000e+000, 6.89886715e-310,
        6.89886715e-310, 6.89886715e-310, 6.89886715e-310],
       [6.89886713e-310, 6.89886715e-310, 6.89886715e-310,
        6.89886715e-310, 6.89886713e-310, 6.89886713e-310],
       [6.89886713e-310, 6.89886715e-310, 6.89886715e-310,
        6.89886713e-310, 6.89886715e-310, 6.89886715e-310],
       [6.89886715e-310, 6.89886713e-310, 6.89886715e-310,
        6.89886715e-310, 6.89886713e-310, 6.89886713e-310]])

In [37]:
y = np.array([[1, 2, 3], [4, 5, 6], [7 , 8, 9]])

In [38]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
y.sum(axis=0)

array([12, 15, 18])

In [40]:
y.sum(axis=1)

array([ 6, 15, 24])

In [41]:
y.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
y.flat

In [44]:
for item in y.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [45]:
y.ndim

2

In [46]:
y.size

9

In [47]:
y.nbytes

72

In [49]:
one = np.array([2,4,22,100,5])

In [50]:
one

array([  2,   4,  22, 100,   5])

In [51]:
one.argmax()

3

In [52]:
one.argmin()

0

In [53]:
one.argsort()

array([0, 1, 4, 2, 3])

In [54]:
two = np.array([[2,4,3],[5,8,9]])

In [55]:
two

array([[2, 4, 3],
       [5, 8, 9]])

In [56]:
two.argmax()

5

In [57]:
two.argmin()

0

In [58]:
two.argsort()

array([[0, 2, 1],
       [0, 1, 2]])

In [59]:
two.argmax(axis = 1)

array([1, 2])

In [60]:
two.argmin(axis = 0)

array([0, 0, 0])

In [61]:
two.argmax(axis = 0)

array([1, 1, 1])

In [62]:
two.argmin(axis = 1)

array([0, 0])

In [63]:
two.ravel()

array([2, 4, 3, 5, 8, 9])

In [68]:
x

array([[2, 3, 1, 0],
       [4, 5, 6, 7],
       [7, 6, 5, 4]])

In [69]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.where(x>3)

(array([1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3]))

In [73]:
np.nonzero(y)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))